#!/sbin/busybox sh

DEVICE=`sh /res/synapse/files/shamu.sh`;

UCI_CONFIG=/res/synapse/config.json;
UCI_ACTION=/res/synapse/actions/;
DEBUG=/res/synapse/debug;
SYNAPSE_SD_DIR=/sdcard/Synapse;

# Mount root as RW to apply tweaks and settings
mount -t rootfs -o remount,rw rootfs;
mount -o remount,rw /;

if [ ! -f $UCI_CONFIG ]; then
	[ ! -d "$SYNAPSE_SD_DIR" ] && mkdir -p "$SYNAPSE_SD_DIR";
	# Use this trigger to reset Synapse settings on boot.
	# Just increment it for cases like default parameters are changed
	# for some drivers and you wish user to use these parameters on boot.
	KERNEL_CURR=20160118-marshmallow;
	
	if [ ! -f "$SYNAPSE_SD_DIR/last_kernel" ]; then
		rm -R /data/data/com.af.synapse/databases;
		echo "$KERNEL_CURR" > $SYNAPSE_SD_DIR/last_kernel;
	else
		KERNEL_LAST=`cat $SYNAPSE_SD_DIR/last_kernel 2> /dev/null`;
		
		if [ "$KERNEL_CURR" != "$KERNEL_LAST" ]; then
			rm -R /data/data/com.af.synapse/databases;
			echo "$KERNEL_CURR" > $SYNAPSE_SD_DIR/last_kernel;
		fi
	fi

	mount -t rootfs -o rw,remount rootfs;
	chmod -R 755 $UCI_ACTION;
	
	if [ ! -f $DEBUG/pvs_bin ]; then
		[ ! -d "$DEBUG" ] && mkdir -p "$DEBUG";
		echo `sh $DEVICE DebugPVS` > $DEBUG/pvs_bin;
	fi
	
	source /res/synapse/config.json.generate > $UCI_CONFIG;
	
	mount -t rootfs -o rw,remount rootfs;
fi;

case "${1}" in
  config)
		cat $UCI_CONFIG;;
  configpath)
		echo $UCI_CONFIG;;
  actionpath)
		echo $UCI_ACTION;;
  reset)
		mount -t rootfs -o rw,remount rootfs;
		rm -f $UCI_CONFIG;
		mount -t rootfs -o rw,remount rootfs;;
esac;
